"""
Pydantic models for shap-to-report.

Three layers:
  AttributionResult  — per-channel SHAP-like attribution (one per anomaly event)
  AnomalyEvent       — the unit of work passed into the LLM pipeline
  SituationalReport  — the pipeline output (confident or degraded)

Channel IDs match SMAP dataset conventions (D-2, A-9, etc.).
Feature names are the 5 statistical aggregations from telemetry-anomdet.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

FEATURE_NAMES: list[str] = ["mean", "std", "min", "max", "slope"]

DegradedMode = Literal[
    "none",
    "shap_unavailable",
    "llm_unavailable",
    "insufficient_context_retrieval",
    "validation_failed",
    "model_low_confidence",
]

AnomalyType = Literal[
    "sensor_fault",
    "actuator_fault",
    "thermal_anomaly",
    "power_anomaly",
    "communication_anomaly",
    "attitude_anomaly",
    "propulsion_anomaly",
    "unknown",
]

SeverityLevel = Literal["low", "medium", "high", "critical"]

Spacecraft = Literal["SMAP", "OPS-SAT"]

Archetype = Literal["concentrated", "mid", "diffuse", "conflicting", "adversarial"]


# ---------------------------------------------------------------------------
# Attribution layer
# ---------------------------------------------------------------------------

class AttributionResult(BaseModel):
    """
    SHAP-like per-feature attribution for a single channel anomaly window.

    feature_names is always FEATURE_NAMES = ["mean", "std", "min", "max", "slope"].
    Included explicitly so the bar-chart renderer can iterate by index without
    hardcoding the order, and so the LLM receives named context.

    feature_attributions are in the same order as feature_names.
    Values are floats (can be negative — negative = pushed score away from anomaly).
    They do NOT need to sum to 1.

    attribution_concentration is the Gini coefficient over abs(feature_attributions),
    in [0, 1]. High = one feature dominates. Low = diffuse across features.
    """

    channel_id: str = Field(description="SMAP channel ID, e.g. 'D-2'")
    feature_names: list[str] = Field(
        description="Statistical feature names, always ['mean','std','min','max','slope']"
    )
    feature_attributions: list[float] = Field(
        description="SHAP-like attribution per feature, same order as feature_names"
    )
    attribution_concentration: float = Field(
        description="Gini coefficient over abs(feature_attributions), in [0, 1]",
        ge=0.0,
        le=1.0,
    )


# ---------------------------------------------------------------------------
# Event layer
# ---------------------------------------------------------------------------

class AnomalyEvent(BaseModel):
    """
    The unit of work passed into the LLM reasoning pipeline.

    Contains everything the pipeline needs:
      - Identity (event_id, spacecraft, channel_id, timestamp)
      - Detection signals (ensemble_score, ensemble_agreement, n_models_in_ensemble)
      - Attribution (AttributionResult)
      - Optional ground truth (only populated for synthetic eval events)
      - Optional SHAP image path (PNG rendered from attribution, sent to vision model)
    """

    # Identity
    event_id: str = Field(description="Unique event identifier, e.g. 'evt_001'")
    spacecraft: Spacecraft = Field(description="Source spacecraft dataset")
    channel_id: str = Field(description="Anomalous telemetry channel, e.g. 'D-2'")
    timestamp: datetime = Field(description="Timestamp of the anomaly window start")
    window_size: int = Field(default=50, description="Window size in samples")
    window_start_index: int = Field(description="Absolute index in source timeseries")

    # Detection signals
    ensemble_score: float = Field(description="Normalized ensemble anomaly score [0, 1]")
    ensemble_agreement: int = Field(description="Number of models that flagged this window")
    n_models_in_ensemble: int = Field(description="Total models in ensemble (denominator)")

    # Attribution
    attribution: AttributionResult = Field(description="SHAP-like per-feature attribution")

    # Optional: SHAP bar chart image path (generated by renderer, sent to vision model)
    shap_image_path: Optional[str] = Field(
        default=None,
        description="Path to rendered SHAP bar chart PNG, if available",
    )

    # Ground truth (None for production; populated for synthetic eval events)
    ground_truth_top_feature: Optional[str] = Field(
        default=None,
        description="Expected top SHAP feature for eval scoring",
    )
    ground_truth_anomaly_type: Optional[AnomalyType] = Field(
        default=None,
        description="Expected anomaly type for eval scoring",
    )
    ground_truth_severity: Optional[SeverityLevel] = Field(
        default=None,
        description="Expected severity for eval scoring",
    )
    ground_truth_narrative: Optional[str] = Field(
        default=None,
        description="Hand-written reference narrative (Day 3 reference reports)",
    )
    archetype: Optional[Archetype] = Field(
        default=None,
        description="Attribution archetype — used to break down eval results by type",
    )


# ---------------------------------------------------------------------------
# Report layer (pipeline output)
# ---------------------------------------------------------------------------

class ProvenanceEntry(BaseModel):
    """A single retrieved chunk that grounded the report."""

    source_body: str = Field(description="Regulatory body or corpus tag, e.g. 'EU_AI_Act'")
    document: str = Field(description="Document name or identifier")
    section: str = Field(description="Section or chunk identifier")
    relevance_score: float = Field(
        description="Cosine similarity score from retrieval", ge=0.0, le=1.0
    )
    text: Optional[str] = Field(
        default=None,
        description="Full text of the retrieved chunk, for display in the UI",
    )


class SituationalReport(BaseModel):
    """
    The primary output of the shap-to-report pipeline.

    When degraded_mode != 'none', all substantive fields are None and the
    report should be rendered as a RefusalCard in the UI.
    """

    # Identity
    event_id: str = Field(description="Identifier of the input event")
    degraded_mode: DegradedMode = Field(
        description="Reason report is degraded, or 'none' if confident"
    )

    # Substantive fields (None when degraded)
    anomaly_type: Optional[AnomalyType] = Field(
        default=None, description="Classified anomaly type"
    )
    severity: Optional[SeverityLevel] = Field(
        default=None, description="Assessed severity level"
    )
    primary_features: Optional[list[str]] = Field(
        default=None,
        description="Top SHAP-attributed features driving the anomaly, e.g. ['mean', 'std']",
    )
    explanation: Optional[str] = Field(
        default=None,
        description="Natural-language explanation grounded in retrieved context",
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Model self-reported confidence [0, 1]",
        ge=0.0,
        le=1.0,
    )
    ensemble_agreement_ratio: Optional[float] = Field(
        default=None,
        description="Fraction of ensemble models that flagged this event [0, 1]",
        ge=0.0,
        le=1.0,
    )
    attribution_concentration: Optional[float] = Field(
        default=None,
        description="Gini coefficient from AttributionResult — high = concentrated",
        ge=0.0,
        le=1.0,
    )
    historical_precedent: Optional[str] = Field(
        default=None,
        description="Reference to the closest historical anomaly from the corpus",
    )
    provenance: Optional[list[ProvenanceEntry]] = Field(
        default=None,
        description="Retrieved chunks that grounded this report",
    )
    operator_assessment: Optional[str] = Field(
        default=None,
        description="Concise operator-facing summary of the situation",
    )
    operator_decision: Optional[str] = Field(
        default=None,
        description=(
            "Decision framing for the operator — observational only, "
            "no prescriptive verbs (verify/check/adjust/recommend/suggest/ensure)"
        ),
    )

    # Refusal metadata (populated when degraded)
    refusal_reason: Optional[str] = Field(
        default=None,
        description="Human-readable explanation of why the report was degraded",
    )
